export const RECEIVE_ALL_MATERIAL = 'RECEIVE_ALL_MATERIAL';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const EDIT_MATERIAL = 'EDIT_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
