export const RUN_CRAWLER = 'RUN_CRAWLER';
export const RECEIVE_NEW_CRAWLER = 'RECEIVE_NEW_CRAWLER';
export const FETCH_CRAWLERS = 'FETCH_CRAWLERS';
export const RECEIVE_ALL_CRAWLERS = 'RECEIVE_ALL_CRAWLERS';