export const RECEIVE_ALL_DIRECTIONS = 'RECEIVE_ALL_DIRECTIONS';
export const ADD_DIRECTION = 'ADD_DIRECTION';
export const EDIT_DIRECTION = 'EDIT_DIRECTION';
export const DELETE_DIRECTION = 'DELETE_DIRECTION';